version: '3'
services:

  mq:
    image: rabbitmq:3.8-management
    ports:
      - $MQ_PORT:5672
      - $MQ_ADMIN_PORT:15672
    environment:
      RABBITMQ_DEFAULT_USER: nrg
      RABBITMQ_DEFAULT_PASS: gottaLottaEnemies
