const path = require('path')
const fs = require('fs')
const { print } = require('@ianwalter/print')
const requireFromString = require('require-from-string')
const devalue = require('devalue')
const prettydiff = require('prettydiff')
const indentString = require('indent-string')
const pkgDir = require('pkg-dir')

prettydiff.options = {
  ...prettydiff.options,
  mode: 'beautify',
  indent_size: 2,
  space_close: true
}

const appModule = module.parent.parent.parent || module.parent.parent
const mainDir = pkgDir.sync(appModule.filename)
const defaultSsrOptions = {
  entry: path.join(mainDir, 'dist/ssr.js'),
  template: path.join(__dirname, '../pageTemplate.html')
}

function serveSsr (options) {
  // Merge the given options with the default options.
  options = Object.assign({}, defaultSsrOptions, options)

  return async (ctx, next) => {
    if (ctx.isNotDev && !options.renderer) {
      // Create the page renderer that will be used by the middleware if it
      // wasn't given on initialization.
      try {
        if (!options.page) {
          options.page = fs.readFileSync(options.template, 'utf8')
        }
        options.renderer = require(options.entry).default(options.page)
      } catch (err) {
        print.warn(err)
      }
    } else if (!ctx.isNotDev) {
      // If not in production mode, use the renderer generated by Webpack so
      // that it can be changed without having to restart the server.
      const fs = ctx.webpack.fileSystem
      const entry = fs.readFileSync(options.entry, 'utf8')
      options.page = fs.readFileSync(options.template, 'utf8')
      options.renderer = requireFromString(entry).default(options.page)
    }

    // Add the "full" URL on the context so that a router can use it with the
    // URL class.
    ctx.fullUrl = ctx.baseUrl.origin + ctx.url

    // TODO: comment
    const result = await options.renderer(ctx)

    // If a string was returned instead of a page object, redirect to it as a
    // URL.
    if (typeof result === 'string') {
      return ctx.redirect(result)
    }

    // If the response body has not already been set, construct the HTML
    // document that will be served.
    if (!ctx.body) {
      let { head = '', css = { code: '' }, html = '', ssr } = result

      // If SSR data was provided, embed it into the page so that it can be used
      // when the client-side application boots and removed from the page if
      // necessary.
      if (ssr) {
        head += `
          <script id="ssrData" type="text/javascript">
            window.__SSR_DATA__ = ${devalue(ssr)}
          </script>
        `
      }

      // Make sure the markup is indented properly.
      // NOTE: Might change this to only be done during development in the
      // future.
      prettydiff.options.source = html
      html = indentString(prettydiff(), 6)

      // Replace the placeholders on the base page template with the code
      // returne by the end-user's SSR entry.
      ctx.body = options.page
        .replace('<!-- head-outlet -->', head)
        .replace('/* css-outlet */', css.code)
        .replace('<!-- html-outlet -->', html)
    }
  }
}

module.exports = { serveSsr }
