version: '3'
services:

  redis:
    image: redis
    ports:
      - "6379:6379"

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRESS_DB=nrg
      - POSTGRES_USER=nrg
      - POSTGRES_PASSWORD=gottaLottaEnemies
