name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:13.8
    timeout-minutes: 5
    env:
      MQ_HOST: rabbitmq
      MQ_PORT: 5672
    services:
      rabbitmq:
        image: rabbitmq:3.8
        ports:
          - 5672:5672
        env:
          RABBITMQ_DEFAULT_USER: nrg
          RABBITMQ_DEFAULT_PASS: gottaLottaEnemies
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: yarn --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
