version: '3'
services:

  mq:
    image: rabbitmq:3.8-management
    ports:
      - "25672:5672"
      - "35672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: nrg
      RABBITMQ_DEFAULT_PASS: gottaLottaEnemies
