version: '3'

volumes:
  pgdata:

services:

  redis:
    image: redis:5.0
    ports:
      - $REDIS_PORT:6379

  db:
    image: postgres:12.16
    stop_signal: SIGINT
    ports:
      - $DB_PORT:5432
    environment:
      POSTGRES_DB: nrg
      POSTGRES_USER: nrg
      POSTGRES_PASSWORD: gottaLottaEnemies
    volumes:
      - pgdata:/var/lib/postgresql/data

  maildev:
    image: djfarrelly/maildev:1.1.0
    ports:
      - $SMTP_PORT:25
      - $MAILDEV_PORT:80
