name: Changeset
on:
  pull_request:
    types: [labeled, synchronize]
jobs:
  changeset:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Add Changeset
        uses: generates/changeset-action@f7092a7748b2836fad756992f2d40e162b955495
        with:
          token: ${{ secrets.GH_PAT }}
      - name: Commit Changes
        uses: generates/commit-action@v1.0.2
        with:
          token: ${{ secrets.GH_PAT }}
