name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      DB_HOST: postgres
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MQ_HOST: rabbitmq
      MQ_PORT: 5672
      SMTP_HOST: maildev
      SMTP_PORT: 25
    services:
      postgres:
        image: postgres:12.3
        env:
          POSTGRES_DB: nrg
          POSTGRES_USER: nrg
          POSTGRES_PASSWORD: gottaLottaEnemies
        # Needed because the postgres container does not provide a health check.
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5 --entrypoint "postgres -c log_statement=all"
      redis:
        image: redis:5.0
        options: --entrypoint redis-server
      rabbitmq:
        image: rabbitmq:3.8
        env:
          RABBITMQ_DEFAULT_USER: nrg
          RABBITMQ_DEFAULT_PASS: gottaLottaEnemies
      maildev:
        image: djfarrelly/maildev
        ports:
          - 1025:25
          - 1080:80
    steps:
      - name: Checkout
        uses: actions/checkout@v1.2.0
      - name: Install
        uses: docker://node:14.5
        with:
          args: yarn --frozen-lockfile
      - name: Lint
        uses: docker://node:14.5
        with:
          args: yarn lint
      - name: Debug
        uses: docker://node:14.5
        with:
          args: yarn nrg print config
      - name: Test
        uses: docker://node:14.5
        with:
          args: yarn test:ci
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1
