name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ianwalter/pnpm:v1.0.0
    timeout-minutes: 5
    env:
      DB_HOST: postgres
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MQ_HOST: rabbitmq
      MQ_PORT: 5672
      SMTP_HOST: maildev
      SMTP_PORT: 25
      MAILDEV_HOST: maildev
      MAILDEV_PORT: 80
    services:
      postgres:
        image: postgres:12.3
        env:
          POSTGRES_DB: nrg
          POSTGRES_USER: nrg
          POSTGRES_PASSWORD: gottaLottaEnemies
        # Needed because the postgres container does not provide a health check.
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:5.0
        options: --entrypoint redis-server
      rabbitmq:
        image: rabbitmq:3.8
        env:
          RABBITMQ_DEFAULT_USER: nrg
          RABBITMQ_DEFAULT_PASS: gottaLottaEnemies
      maildev:
        image: djfarrelly/maildev:1.1.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: pnpm i -r
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm -r test
